version: "3.8"

services:
  frontend:
    image: frontend-project
    ports:
      - 5000:5000
  backend:
    image: backend-project
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
    ports:
      - 8080:8080
  redis:
    image: redis
  db:
    image: postgres:13.2-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./database:/var/lib/postgresql/data
  proxy:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend